# Generated by Django 5.1.5 on 2025-01-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_up", models.PositiveBigIntegerField(editable=False)),
                (
                    "image",
                    models.ImageField(upload_to="funicular/", verbose_name="Image"),
                ),
            ],
        ),
    ]
