# Generated by Django 5.1.5 on 2025-03-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funicular_down", "0002_alter_entry_options_alter_entry_id_up"),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="Address")),
                ("token", models.CharField(max_length=40, verbose_name="Token Key")),
            ],
            options={
                "verbose_name": "Server",
                "verbose_name_plural": "Servers",
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="server",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="funicular_down.server",
                verbose_name="Server",
            ),
            preserve_default=False,
        ),
    ]
