# Generated by Django 5.1.5 on 2025-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funicular_down", "0003_server_entry_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
