# Generated by Django 5.1.5 on 2025-03-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funicular_down", "0004_server_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="id_up",
            field=models.PositiveBigIntegerField(editable=False),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("server", "id_up"), name="unique_server_to_id"
            ),
        ),
    ]
